# Generated by Django 3.2.16 on 2023-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, upload_to='variant/'),
        ),
    ]
