# Generated by Django 3.2.16 on 2023-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='web_id',
            field=models.CharField(default='3e3', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
