# Generated by Django 4.1.5 on 2023-02-17 11:23

import apps.products.utils.units
from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='weight',
            field=django_measurement.models.MeasurementField(default=0.0, measurement=apps.products.utils.units.Mass),
        ),
    ]
