# Generated by Django 4.1.5 on 2023-01-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='code',
        ),
    ]
