# Generated by Django 4.1.5 on 2023-02-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'ProductAttribute', 'verbose_name_plural': 'ProductAttributes'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'ProductAttributeValue', 'verbose_name_plural': 'ProductAttributeValue'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalues',
            options={'verbose_name': 'ProductAttributeValues', 'verbose_name_plural': 'ProductAttributeValues'},
        ),
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name': 'ProductInventory', 'verbose_name_plural': 'ProductInventory'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'ProductType', 'verbose_name_plural': 'ProductTypes'},
        ),
        migrations.AlterModelOptions(
            name='producttypeattribute',
            options={'verbose_name': 'ProductTypeAttribute', 'verbose_name_plural': 'ProductTypeAttribute'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
    ]
