# Generated by Django 3.2.16 on 2023-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
