# Generated by Django 4.1.5 on 2023-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_related_product_product_is_recommended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='installment_plan',
            field=models.CharField(default='2', max_length=250),
            preserve_default=False,
        ),
    ]
