# Generated by Django 4.1.5 on 2023-02-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalues',
            name='attributevalues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributevaluess', to='products.productattributevalue', verbose_name='attributevalues'),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='productinventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productattributevaluess', to='products.productinventory', verbose_name='productinventory'),
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='product_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productattribute', to='products.productattribute', verbose_name='attributevalues'),
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producttype', to='products.producttype', verbose_name='productinventory'),
        ),
    ]
