# Generated by Django 4.1.5 on 2023-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_size_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='image_id',
        ),
        migrations.AddField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
