# Generated by Django 4.1.5 on 2023-03-06 11:07

import apps.products.utils.units
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_productinventory_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='sku')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_default', models.BooleanField(default=False, verbose_name='is_default')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='price')),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='sale_price')),
                ('installment_plan', models.CharField(max_length=250, verbose_name='installment_plan')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='is_on_sale')),
                ('alifshop', models.BooleanField(default=False, verbose_name='alifshop')),
                ('weight', django_measurement.models.MeasurementField(blank=True, measurement=apps.products.utils.units.Mass, null=True, verbose_name='weight')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('status', models.CharField(choices=[('В прогрессе', 'Process'), ('Успешно', 'Success'), ('Ошибка', 'Failed'), ('Удалено', 'Deleted')], default='В прогрессе', max_length=50, verbose_name='status')),
                ('attribute_values', models.ManyToManyField(related_name='new_product_attribute_values', to='products.productattributevalue', verbose_name='attribute_values')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_brand', to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='category')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_type', to='products.producttype', verbose_name='product_type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_products', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'NewProduct',
                'verbose_name_plural': 'NewProducts',
            },
        ),
    ]
