# Generated by Django 4.1.5 on 2023-02-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productattributevalues_attributevalues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product_inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='products.productinventory', verbose_name='product_inventory'),
        ),
    ]
