# Generated by Django 4.1.5 on 2023-01-29 09:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productinventory_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='web_id',
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
