# Generated by Django 4.1.5 on 2023-03-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_product'),
        ('products', '0005_newmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productallmodel',
            name='atributes_value',
        ),
        migrations.RemoveField(
            model_name='productallmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productallmodel',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_type',
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'product_all', 'verbose_name_plural': 'product_alls'},
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalues',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_inventory',
        ),
        migrations.AddField(
            model_name='productattributevalues',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productattributevaluess', to='products.newproductmodel', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='products.newproductmodel', verbose_name='product_inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttypeattribute',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producttype', to='products.producttype', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.newproductmodel', verbose_name='ratings'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.newproductmodel', verbose_name='wishlists'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalues',
            unique_together={('attributevalues', 'product')},
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAllModel',
        ),
        migrations.RemoveField(
            model_name='productattributevalues',
            name='productinventory',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
