# Generated by Django 4.1.5 on 2023-02-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
