# Generated by Django 4.1.5 on 2023-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_media_img_url_alter_media_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price'),
        ),
    ]
