# Generated by Django 4.1.5 on 2023-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productallmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productallmodel',
            name='atributes_value',
        ),
        migrations.AddField(
            model_name='productallmodel',
            name='atributes_value',
            field=models.ManyToManyField(to='products.productattributevalue'),
        ),
    ]
