# Generated by Django 4.1.5 on 2023-02-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productinventory_price_and_more'),
        ('products', '0007_alter_productinventory_price'),
    ]

    operations = [
    ]
