# Generated by Django 4.1.5 on 2023-02-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_test_image_alter_productinventory_product'),
        ('products', '0007_alter_productinventory_weight'),
    ]

    operations = [
    ]
