# Generated by Django 4.1.5 on 2023-02-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productallmodel_atributes_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
