# Generated by Django 4.1.5 on 2023-02-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20230227_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.productinventory', verbose_name='product_inventory'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='products.producttype', verbose_name='product_type'),
        ),
    ]
