# Generated by Django 4.1.5 on 2023-03-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_title_newproductmodel_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductmodel',
            name='attribute_values',
            field=models.ManyToManyField(related_name='attributes', to='products.productattributevalue', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='title_en',
            field=models.CharField(max_length=300, verbose_name='title_en'),
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='title_ru',
            field=models.CharField(max_length=300, verbose_name='title_ru'),
        ),
    ]
