# Generated by Django 4.1.5 on 2023-02-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20230227_1553'),
        ('products', '0009_alter_media_product_inventory_and_more'),
    ]

    operations = [
    ]
