# Generated by Django 4.1.5 on 2023-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_newproductmodel_attribute_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='descriptions',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
    ]
