# Generated by Django 4.1.5 on 2023-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_newproductmodel_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('В прогрессе', 'Process'), ('Успешно', 'Success'), ('Ошибка', 'Failed'), ('Удалено', 'Deleted')], default='В прогрессе', max_length=50, verbose_name='status'),
        ),
    ]
