# Generated by Django 4.1.5 on 2023-03-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_newproductmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductmodel',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='products.productattributevalue', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='product_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_product_type', to='products.producttype', verbose_name='product_type'),
        ),
    ]
