# Generated by Django 4.1.5 on 2023-03-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_newproductmodel_attribute_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductmodel',
            name='attribute_values',
            field=models.ManyToManyField(related_name='attributes', to='products.productattributevalue', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='new_product_type', to='products.producttype', verbose_name='product_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='status',
            field=models.CharField(choices=[('В прогрессе', 'Process'), ('Успешно', 'Success'), ('Ошибка', 'Failed'), ('Удалено', 'Deleted')], default='В прогрессе', max_length=50, verbose_name='status'),
        ),
    ]
