# Generated by Django 4.1.5 on 2023-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='logo')),
                ('phonenumbers', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('site_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='site type')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('link', models.URLField(blank=True, null=True, verbose_name='instagram link')),
            ],
        ),
    ]
