# Generated by Django 4.1.5 on 2023-02-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phonenumbers',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='site type'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='telegram link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='youtube link'),
        ),
    ]
