# Generated by Django 4.1.5 on 2023-02-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_alter_sitesettings_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='instagram',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='youtube',
        ),
    ]
