# Generated by Django 4.1.5 on 2023-02-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='NAXT_STATUS',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='PAY_STATUS',
            field=models.BooleanField(default=False),
        ),
    ]
