# Generated by Django 4.1.5 on 2023-03-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='generate_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
