# Generated by Django 4.1.5 on 2023-02-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cart',
            field=models.ManyToManyField(blank=True, to='cart.cartitem', verbose_name='cart'),
        ),
    ]
