# Generated by Django 4.1.5 on 2023-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
        ('checkout', '0003_rename_order_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ManyToManyField(null=True, to='cart.cartitem'),
        ),
    ]
