# Generated by Django 4.1.5 on 2023-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_generate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
