# Generated by Django 4.1.5 on 2023-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkout_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='total_price',
        ),
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
