# Generated by Django 4.1.5 on 2023-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_checkout_total_price_checkout_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
