# Generated by Django 4.1.5 on 2023-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_checkout_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCheckoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAY_STATUS', models.BooleanField(default=False, verbose_name='PAY_STATUS')),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('generate_link', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'NewCheckout',
                'verbose_name_plural': 'NewCheckout',
            },
        ),
    ]
