# Generated by Django 4.1.5 on 2023-03-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_newcheckoutmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCheckoutModel',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='order_id',
        ),
    ]
