# Generated by Django 4.1.5 on 2023-02-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
