# Generated by Django 4.1.5 on 2023-01-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default=223, max_length=40),
            preserve_default=False,
        ),
    ]
