# Generated by Django 4.1.5 on 2023-03-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('outside', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productinventory', verbose_name='product'),
        ),
    ]
