# Generated by Django 4.1.5 on 2023-01-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0004_add_to_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_to_cart',
        ),
    ]
