# Generated by Django 4.1.5 on 2023-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0004_alter_brand_options_alter_slider_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='slug',
        ),
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.SlugField(default='1', max_length=250, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(default='1', max_length=250, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='url',
            field=models.URLField(default='1', max_length=250, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
