# Generated by Django 4.1.5 on 2023-03-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_newmedia'),
        ('outside', '0004_alter_add_to_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.newproductmodel', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='br_product', to='products.newproductmodel', verbose_name='product'),
        ),
    ]
