# Generated by Django 4.1.5 on 2023-02-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0005_remove_brand_slug_remove_slider_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.SlugField(max_length=250, verbose_name='url'),
        ),
    ]
