# Generated by Django 4.1.5 on 2023-02-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0007_alter_brand_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.URLField(max_length=250, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(max_length=250, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='url',
            field=models.URLField(max_length=250, verbose_name='url'),
        ),
    ]
