# Generated by Django 4.1.5 on 2023-03-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaYme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchattransactionsmodel',
            old_name='order_id',
            new_name='payment_id',
        ),
    ]
