# Generated by Django 4.1.5 on 2023-03-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaYme', '0002_rename_order_id_merchattransactionsmodel_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchattransactionsmodel',
            old_name='payment_id',
            new_name='order_id',
        ),
    ]
