# Generated by Django 4.1.5 on 2023-01-21 12:39

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('buyer_id', models.CharField(max_length=50)),
                ('user_status', models.PositiveIntegerField(choices=[(0, 'не найден'), (1, 'нужно добавить карту'), (2, 'ожидание верификации'), (4, 'верифицирован'), (5, 'нужно фото паспорта'), (8, 'отказано в верификации'), (10, 'нужно фото селфи с паспортом'), (11, 'нужно фото паспорта со страницей прописки'), (12, 'добавить доверителя')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED'), ('FULFILLED', 'FULFILLED'), ('UNFULFILLED', 'UNFULFILLED')], default='PENDING', max_length=12)),
                ('contract_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('limit', models.PositiveSmallIntegerField()),
                ('payment_date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buyer_phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
